hard_tabs = true
blank_lines_lower_bound = 0
blank_lines_upper_bound = 10
fn_single_line = true
max_width = 80
fn_call_width = 60
format_generated_files = false
imports_granularity = "Item"
group_imports = "One"
wrap_comments = true
imports_layout = "Vertical"
# Foo, Bar, Baz {} if Baz has a new line, all are on a new line
# overflow_delimited_expr = true
use_field_init_shorthand = true
